// eval/fixtures/nuxt-pms/pages/guests.vue
<script setup lang="ts">
import { computed } from 'vue'

import type { Guest } from '#shared/types'

useHead({ title: 'Harbor PMS · Guests' })

const { data: guestsData } = await useFetch<Guest[]>('/api/guests', {
  default: () => [],
})
const guests = computed(() => guestsData.value ?? [])
</script>

<template>
  <div class="page page-wrap">
    <div class="page-head">
      <div>
        <p class="kicker">Directory</p>
        <h1 class="title">Guests</h1>
        <p class="subtitle">
          {{ guests.length }} unique guest{{ guests.length === 1 ? '' : 's' }}
        </p>
      </div>
      <NuxtLink to="/reservations" class="btn btn-ghost">
        View reservations
      </NuxtLink>
    </div>

    <div v-if="guests.length === 0" class="panel empty">
      No guests yet. They'll appear here after the first booking.
    </div>

    <div v-else class="panel table-wrap" style="padding: 0">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th class="text-right">Stays</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="guest in guests" :key="guest.email">
            <td style="font-weight: 600">{{ guest.name }}</td>
            <td><a :href="`mailto:${guest.email}`">{{ guest.email }}</a></td>
            <td><a :href="`tel:${guest.phone}`">{{ guest.phone }}</a></td>
            <td class="text-right" style="font-weight: 600">
              {{ guest.reservationCount }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// eval/fixtures/sveltekit-pms/src/routes/guests/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types'

  let { data }: PageProps = $props()
</script>

<div class="page-wrap" style="padding-block: 3rem;">
  <div class="rise-in header-row">
    <div>
      <p class="island-kicker">Directory</p>
      <h1 class="display-title page-title">Guests</h1>
      <p class="muted" style="margin-top: 0.5rem;">
        {data.guests.length} unique guest{data.guests.length === 1 ? '' : 's'}
      </p>
    </div>
    <a href="/reservations" class="btn btn-ghost">View reservations</a>
  </div>

  {#if data.guests.length === 0}
    <div class="island-shell rise-in empty-state">
      No guests yet. They'll appear here after the first booking.
    </div>
  {:else}
    <div class="island-shell rise-in table-wrap">
      <table class="data-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th style="text-align: right;">Stays</th>
          </tr>
        </thead>
        <tbody>
          {#each data.guests as guest (guest.email)}
            <tr>
              <td style="font-weight: 600; color: var(--sea-ink);">
                {guest.name}
              </td>
              <td><a href="mailto:{guest.email}">{guest.email}</a></td>
              <td><a href="tel:{guest.phone}">{guest.phone}</a></td>
              <td style="text-align: right; font-weight: 600; color: var(--sea-ink);">
                {guest.reservationCount}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>

<style>
  .header-row {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-end;
    justify-content: space-between;
    gap: 1rem;
  }
  .page-title {
    margin-top: 0.5rem;
    font-size: 2.25rem;
    font-weight: 700;
    color: var(--sea-ink);
  }
  .empty-state {
    margin-top: 2rem;
    padding: 3rem;
    text-align: center;
    color: var(--sea-ink-soft);
  }
  .table-wrap {
    margin-top: 2rem;
    overflow: hidden;
  }
</style>
