// eval/fixtures/sveltekit-pms/src/routes/reservations/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms'

  import { formatDate, nights } from '$lib/format'
  import { SPACE_KIND_LABELS } from '$lib/space-kinds'
  import type { ReservationStatus } from '$lib/server/db'
  import type { ReservationRow } from '$lib/server/queries'
  import type { Space } from '$lib/server/db'
  import type { PageProps } from './$types'

  let { data, form }: PageProps = $props()

  let busyId = $state<number | null>(null)

  const STATUS_LABEL: Record<ReservationStatus, string> = {
    pending: 'Pending',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
  }

  const upcoming = $derived(
    data.reservations.filter((r) => r.status !== 'cancelled').length,
  )
  const unassigned = $derived(
    data.reservations.filter(
      (r) => r.status !== 'cancelled' && r.spaceId === null,
    ).length,
  )

  // Every mutation on this page is a small form action; this wires the shared
  // busy state + progressive enhancement, so an assignment race surfaces its
  // server message inline instead of reloading the page.
  const submit = (id: number) => () => {
    busyId = id
    return async ({ update }: { update: () => Promise<void> }) => {
      await update()
      busyId = null
    }
  }

  /**
   * Archived spaces stay selectable only where they're already assigned, so an
   * existing booking isn't silently reassigned by rendering the dropdown.
   */
  const spaceOptions = (reservation: ReservationRow): Array<Space> =>
    data.spaces.filter(
      (space) => space.status === 'active' || space.id === reservation.spaceId,
    )
</script>

<div class="page-wrap" style="padding-block: 3rem;">
  <div class="rise-in header-row">
    <div>
      <p class="island-kicker">Front desk</p>
      <h1 class="display-title page-title">Reservations</h1>
      <p class="muted" style="margin-top: 0.5rem;">
        {data.reservations.length} total · {upcoming} active{unassigned
          ? ` · ${unassigned} awaiting a space`
          : ''}
      </p>
    </div>
    <div class="header-actions">
      <a href="/spaces" class="btn btn-ghost">Manage spaces</a>
      <a href="/guests" class="btn btn-ghost">See all guests</a>
      <a href="/" class="btn btn-primary">+ New reservation</a>
    </div>
  </div>

  {#if data.reservations.length === 0}
    <div class="island-shell rise-in empty-state">
      No reservations yet. Once guests book, they'll show up here.
    </div>
  {:else}
    <div class="rise-in card-list">
      {#each data.reservations as reservation (reservation.id)}
        <article class="feature-card">
          <div class="card-top">
            <div class="card-main">
              <div class="card-heading">
                <h2 class="guest-name">{reservation.guestName}</h2>
                <span class="badge badge-{reservation.status}">
                  {STATUS_LABEL[reservation.status]}
                </span>
                <span class="muted reservation-id">#{reservation.id}</span>
              </div>

              <div class="card-contact muted">
                <a href="mailto:{reservation.email}">{reservation.email}</a>
                <a href="tel:{reservation.phone}">{reservation.phone}</a>
                <span>
                  {reservation.partySize} guest{reservation.partySize === 1
                    ? ''
                    : 's'}
                </span>
              </div>

              <p class="card-dates">
                {formatDate(reservation.checkIn)} → {formatDate(
                  reservation.checkOut,
                )}
                <span class="muted" style="font-weight: 400;">
                  ({nights(reservation.checkIn, reservation.checkOut)} night{nights(
                    reservation.checkIn,
                    reservation.checkOut,
                  ) === 1
                    ? ''
                    : 's'})
                </span>
              </p>

              {#if reservation.notes}
                <p class="card-notes muted">"{reservation.notes}"</p>
              {/if}

              <!-- Assigned space — where an integration later surfaces access
                   (e.g. a PIN code or mobile key for the guest's stay). -->
              <form
                method="POST"
                action="?/assignSpace"
                class="space-assign"
                use:enhance={submit(reservation.id)}
              >
                <input type="hidden" name="id" value={reservation.id} />
                <span class="island-kicker">Space</span>
                <select
                  name="spaceId"
                  class="input space-select"
                  value={reservation.spaceId === null
                    ? ''
                    : String(reservation.spaceId)}
                  disabled={busyId === reservation.id}
                  onchange={(event) => event.currentTarget.form?.requestSubmit()}
                >
                  <option value="">Unassigned</option>
                  {#each spaceOptions(reservation) as space (space.id)}
                    <option value={String(space.id)}>
                      {space.name} · {SPACE_KIND_LABELS[space.kind]} · sleeps {space.capacity}{space.status ===
                      'archived'
                        ? ' (archived)'
                        : ''}
                    </option>
                  {/each}
                </select>
                {#if reservation.spaceId === null}
                  <span class="muted" style="font-size: 0.875rem;"
                    >Not assigned yet</span
                  >
                {/if}
              </form>

              {#if form?.errorId === reservation.id && form.message}
                <p class="error-text" style="margin-top: 0.5rem;">
                  {form.message}
                </p>
              {/if}
            </div>

            <div class="card-actions">
              {#if reservation.status !== 'confirmed'}
                <form
                  method="POST"
                  action="?/updateStatus"
                  use:enhance={submit(reservation.id)}
                >
                  <input type="hidden" name="id" value={reservation.id} />
                  <input type="hidden" name="status" value="confirmed" />
                  <button
                    type="submit"
                    class="btn btn-sm btn-confirm"
                    disabled={busyId === reservation.id}
                  >
                    Confirm
                  </button>
                </form>
              {/if}
              {#if reservation.status !== 'cancelled'}
                <form
                  method="POST"
                  action="?/updateStatus"
                  use:enhance={submit(reservation.id)}
                >
                  <input type="hidden" name="id" value={reservation.id} />
                  <input type="hidden" name="status" value="cancelled" />
                  <button
                    type="submit"
                    class="btn btn-sm btn-ghost"
                    disabled={busyId === reservation.id}
                  >
                    Cancel
                  </button>
                </form>
              {/if}
              <form
                method="POST"
                action="?/delete"
                use:enhance={submit(reservation.id)}
                onsubmit={(event) => {
                  if (
                    !confirm(
                      `Delete reservation #${reservation.id}? This cannot be undone.`,
                    )
                  )
                    event.preventDefault()
                }}
              >
                <input type="hidden" name="id" value={reservation.id} />
                <button
                  type="submit"
                  class="btn btn-sm btn-danger"
                  disabled={busyId === reservation.id}
                >
                  Delete
                </button>
              </form>
            </div>
          </div>
        </article>
      {/each}
    </div>
  {/if}
</div>

<style>
  .header-row {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-end;
    justify-content: space-between;
    gap: 1rem;
  }
  .page-title {
    margin-top: 0.5rem;
    font-size: 2.25rem;
    font-weight: 700;
    color: var(--sea-ink);
  }
  .header-actions {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
  }
  .empty-state {
    margin-top: 2rem;
    padding: 3rem;
    text-align: center;
    color: var(--sea-ink-soft);
  }
  .card-list {
    margin-top: 2rem;
    display: grid;
    gap: 1rem;
  }
  .card-top {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
  }
  .card-heading {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.75rem;
  }
  .guest-name {
    font-size: 1.125rem;
    font-weight: 700;
    color: var(--sea-ink);
  }
  .reservation-id {
    font-size: 0.875rem;
  }
  .card-contact {
    margin-top: 0.5rem;
    display: flex;
    flex-wrap: wrap;
    gap: 0.25rem 1.5rem;
    font-size: 0.875rem;
  }
  .card-dates {
    margin-top: 0.5rem;
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--sea-ink);
  }
  .card-notes {
    margin-top: 0.5rem;
    max-width: 60ch;
    font-size: 0.875rem;
    font-style: italic;
  }
  .space-assign {
    margin-top: 0.75rem;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
  }
  .space-select {
    width: auto;
    padding: 0.375rem 0.625rem;
    font-size: 0.875rem;
    font-weight: 600;
  }
  .card-actions {
    display: flex;
    flex-shrink: 0;
    flex-direction: column;
    align-items: flex-end;
    gap: 0.5rem;
  }
</style>

// eval/fixtures/nuxt-pms/pages/reservations.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

import { messageFromError } from '#shared/errors'
import { SPACE_KIND_LABELS } from '#shared/space-kinds'
import type {
  ReservationRow,
  ReservationStatus,
  Space,
} from '#shared/types'

useHead({ title: 'Harbor PMS · Reservations' })

// The front desk: every reservation with its guest, status, dates, and assigned
// space. This is where a smart-lock integration would later surface access for a
// stay — issuing a PIN or a mobile key once a reservation is confirmed.
const { data: reservationsData, refresh: refreshReservations } = await useFetch<
  ReservationRow[]
>('/api/reservations', { default: () => [] })
const { data: spacesData } = await useFetch<Space[]>('/api/spaces', {
  default: () => [],
})

const reservations = computed(() => reservationsData.value ?? [])
const spaces = computed(() => spacesData.value ?? [])

const busyId = ref<number | null>(null)
const rowError = ref<{ id: number; message: string } | null>(null)

const upcoming = computed(
  () => reservations.value.filter((r) => r.status !== 'cancelled').length,
)
const unassigned = computed(
  () =>
    reservations.value.filter(
      (r) => r.status !== 'cancelled' && r.space_id === null,
    ).length,
)

const STATUS_META: Record<ReservationStatus, { label: string; cls: string }> = {
  pending: { label: 'Pending', cls: 'badge-pending' },
  confirmed: { label: 'Confirmed', cls: 'badge-confirmed' },
  cancelled: { label: 'Cancelled', cls: 'badge-cancelled' },
}

// Run a mutation for one row, surfacing its error inline.
async function run(id: number, action: () => Promise<unknown>) {
  busyId.value = id
  rowError.value = null
  try {
    await action()
    await refreshReservations()
  } catch (err) {
    rowError.value = { id, message: messageFromError(err) }
  } finally {
    busyId.value = null
  }
}

function setStatus(id: number, status: ReservationStatus) {
  return run(id, () =>
    $fetch(`/api/reservations/${id}/status`, { method: 'POST', body: { status } }),
  )
}

function setSpace(id: number, spaceId: number | null) {
  return run(id, () =>
    $fetch(`/api/reservations/${id}/space`, {
      method: 'POST',
      body: { spaceId },
    }),
  )
}

function onSpaceChange(id: number, event: Event) {
  const value = (event.target as HTMLSelectElement).value
  setSpace(id, value === '' ? null : Number(value))
}

function remove(id: number) {
  if (!window.confirm(`Delete reservation #${id}? This cannot be undone.`))
    return
  return run(id, () =>
    $fetch(`/api/reservations/${id}`, { method: 'DELETE' }),
  )
}

// Archived spaces stay selectable only where they're already assigned, so an
// existing booking isn't silently reassigned by rendering the dropdown.
function spaceOptions(reservation: ReservationRow): Space[] {
  return spaces.value.filter(
    (space) => space.status === 'active' || space.id === reservation.space_id,
  )
}

// Deterministic formatting (no locale) so SSR and client markup match.
const MONTHS = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
]

function fmt(iso: string) {
  const [y, m, d] = iso.split('-').map(Number)
  if (!y || !m || !d) return iso
  return `${MONTHS[m - 1]} ${d}, ${y}`
}

function nights(checkIn: string, checkOut: string) {
  const toUtc = (iso: string) => {
    const [y, m, d] = iso.split('-').map(Number)
    return Date.UTC(y, m - 1, d)
  }
  return Math.max(0, Math.round((toUtc(checkOut) - toUtc(checkIn)) / 86_400_000))
}
</script>

<template>
  <div class="page page-wrap">
    <div class="page-head">
      <div>
        <p class="kicker">Front desk</p>
        <h1 class="title">Reservations</h1>
        <p class="subtitle">
          {{ reservations.length }} total · {{ upcoming }} active<template
            v-if="unassigned"
          >
            · {{ unassigned }} awaiting a space</template
          >
        </p>
      </div>
      <div class="actions-row">
        <NuxtLink to="/spaces" class="btn btn-ghost">Manage spaces</NuxtLink>
        <NuxtLink to="/guests" class="btn btn-ghost">See all guests</NuxtLink>
        <NuxtLink to="/" class="btn btn-primary">+ New reservation</NuxtLink>
      </div>
    </div>

    <div v-if="reservations.length === 0" class="panel empty">
      No reservations yet. Once guests book, they'll show up here.
    </div>

    <div v-else class="stack" style="margin-top: 2rem">
      <article v-for="r in reservations" :key="r.id" class="card">
        <div class="card-head">
          <div>
            <div class="chip-row">
              <h2 class="card-title">{{ r.guest_name }}</h2>
              <span class="badge" :class="STATUS_META[r.status].cls">
                {{ STATUS_META[r.status].label }}
              </span>
              <span class="muted">#{{ r.id }}</span>
            </div>

            <div class="meta-row">
              <a :href="`mailto:${r.email}`">{{ r.email }}</a>
              <a :href="`tel:${r.phone}`">{{ r.phone }}</a>
              <span>{{ r.party_size }} guest{{ r.party_size === 1 ? '' : 's' }}</span>
            </div>

            <p style="margin-top: 0.5rem; font-size: 0.9rem; font-weight: 500">
              {{ fmt(r.check_in) }} → {{ fmt(r.check_out) }}
              <span class="muted">
                ({{ nights(r.check_in, r.check_out) }} night{{
                  nights(r.check_in, r.check_out) === 1 ? '' : 's'
                }})
              </span>
            </p>

            <p v-if="r.notes" class="note">"{{ r.notes }}"</p>

            <div class="space-select">
              <span class="kicker">Space</span>
              <select
                class="select"
                :value="r.space_id === null ? '' : String(r.space_id)"
                :disabled="busyId === r.id"
                @change="onSpaceChange(r.id, $event)"
              >
                <option value="">Unassigned</option>
                <option
                  v-for="space in spaceOptions(r)"
                  :key="space.id"
                  :value="String(space.id)"
                >
                  {{ space.name }} · {{ SPACE_KIND_LABELS[space.kind] }} · sleeps
                  {{ space.capacity
                  }}{{ space.status === 'archived' ? ' (archived)' : '' }}
                </option>
              </select>
              <span v-if="r.space_id === null" class="muted">
                Not assigned yet
              </span>
            </div>

            <p v-if="rowError?.id === r.id" class="form-error" style="margin-top: 0.5rem">
              {{ rowError.message }}
            </p>
          </div>

          <div class="card-actions">
            <button
              v-if="r.status !== 'confirmed'"
              type="button"
              class="btn btn-sm btn-confirm"
              :disabled="busyId === r.id"
              @click="setStatus(r.id, 'confirmed')"
            >
              Confirm
            </button>
            <button
              v-if="r.status !== 'cancelled'"
              type="button"
              class="btn btn-sm btn-ghost"
              :disabled="busyId === r.id"
              @click="setStatus(r.id, 'cancelled')"
            >
              Cancel
            </button>
            <button
              type="button"
              class="btn btn-sm btn-danger"
              :disabled="busyId === r.id"
              @click="remove(r.id)"
            >
              Delete
            </button>
          </div>
        </div>
      </article>
    </div>
  </div>
</template>
