// eval/fixtures/sveltekit-pms/src/routes/spaces/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms'

  import SpaceForm from '$lib/SpaceForm.svelte'
  import { formatRate } from '$lib/format'
  import { SPACE_KIND_LABELS } from '$lib/space-kinds'
  import type { Space } from '$lib/server/db'
  import type { PageProps } from './$types'

  let { data, form }: PageProps = $props()

  let editingId = $state<number | null>(null)
  let busyId = $state<number | null>(null)

  const active = $derived(data.spaces.filter((s) => s.status === 'active'))
  const archived = $derived(data.spaces.filter((s) => s.status === 'archived'))
  const beds = $derived(active.reduce((total, s) => total + s.capacity, 0))

  // Route the last action's validation errors to the form that produced them.
  const createErrors = $derived(
    form?.form === 'create' ? (form.errors ?? {}) : {},
  )
  const createFormError = $derived(
    form?.form === 'create' ? (form.formError ?? null) : null,
  )
  const editErrors = (id: number) =>
    form?.form === 'update' && form.id === id ? (form.errors ?? {}) : {}
  const editFormError = (id: number) =>
    form?.form === 'update' && form.id === id ? (form.formError ?? null) : null

  const nextStatus = (space: Space) =>
    space.status === 'active' ? 'archived' : 'active'
</script>

<div class="page-wrap" style="padding-block: 3rem;">
  <div class="rise-in header-row">
    <div>
      <p class="island-kicker">Inventory</p>
      <h1 class="display-title page-title">Spaces</h1>
      <p class="muted" style="margin-top: 0.5rem;">
        {active.length} bookable · sleeps {beds}{archived.length
          ? ` · ${archived.length} archived`
          : ''}
      </p>
    </div>
    <a href="/reservations" class="btn btn-ghost">View reservations</a>
  </div>

  <SpaceForm
    action="?/create"
    title="Add a space"
    submitLabel="Add space"
    errors={createErrors}
    formError={createFormError}
  />

  {#if data.spaces.length === 0}
    <div class="island-shell rise-in empty-state">
      No spaces yet. Add your first room above — guests can't be assigned one
      until you do.
    </div>
  {:else}
    <div class="rise-in card-list">
      {#each data.spaces as space (space.id)}
        {#if editingId === space.id}
          <SpaceForm
            action="?/update"
            title={`Edit ${space.name}`}
            submitLabel="Save changes"
            {space}
            errors={editErrors(space.id)}
            formError={editFormError(space.id)}
            oncancel={() => (editingId = null)}
          />
        {:else}
          {@const rate = formatRate(space.rateCents)}
          <article class="feature-card" class:archived={space.status === 'archived'}>
            <div class="card-top">
              <div>
                <div class="card-heading">
                  <h2 class="space-name">{space.name}</h2>
                  <span class="badge badge-kind">
                    {SPACE_KIND_LABELS[space.kind]}
                  </span>
                  {#if space.status === 'archived'}
                    <span class="badge badge-archived">Archived</span>
                  {/if}
                </div>
                <div class="card-facts muted">
                  <span>
                    Sleeps {space.capacity} guest{space.capacity === 1 ? '' : 's'}
                  </span>
                  <span>{rate ? `${rate} / night` : 'No rate set'}</span>
                </div>
                {#if space.notes}
                  <p class="card-notes muted">{space.notes}</p>
                {/if}
              </div>

              <div class="card-actions">
                <button
                  type="button"
                  class="btn btn-sm btn-ghost"
                  onclick={() => (editingId = space.id)}
                >
                  Edit
                </button>
                <form
                  method="POST"
                  action="?/setStatus"
                  use:enhance={() => {
                    busyId = space.id
                    return async ({ update }) => {
                      await update()
                      busyId = null
                    }
                  }}
                >
                  <input type="hidden" name="id" value={space.id} />
                  <input type="hidden" name="status" value={nextStatus(space)} />
                  <button
                    type="submit"
                    class="btn btn-sm btn-ghost"
                    disabled={busyId === space.id}
                  >
                    {space.status === 'archived' ? 'Restore' : 'Archive'}
                  </button>
                </form>
              </div>
            </div>
          </article>
        {/if}
      {/each}
    </div>
  {/if}
</div>

<style>
  .header-row {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-end;
    justify-content: space-between;
    gap: 1rem;
  }
  .page-title {
    margin-top: 0.5rem;
    font-size: 2.25rem;
    font-weight: 700;
    color: var(--sea-ink);
  }
  .empty-state {
    margin-top: 2rem;
    padding: 3rem;
    text-align: center;
    color: var(--sea-ink-soft);
  }
  .card-list {
    margin-top: 2rem;
    display: grid;
    gap: 1rem;
  }
  .feature-card.archived {
    opacity: 0.6;
  }
  .card-top {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
  }
  .card-heading {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.75rem;
  }
  .space-name {
    font-size: 1.125rem;
    font-weight: 700;
    color: var(--sea-ink);
  }
  .card-facts {
    margin-top: 0.5rem;
    display: flex;
    flex-wrap: wrap;
    gap: 0.25rem 1.5rem;
    font-size: 0.875rem;
  }
  .card-notes {
    margin-top: 0.5rem;
    max-width: 60ch;
    font-size: 0.875rem;
    font-style: italic;
  }
  .card-actions {
    display: flex;
    flex-shrink: 0;
    flex-direction: column;
    align-items: flex-end;
    gap: 0.5rem;
  }
</style>

// eval/fixtures/nuxt-pms/pages/spaces.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

import { formatRate } from '#shared/format'
import type { SpaceInput } from '#shared/schemas'
import { SPACE_KIND_LABELS } from '#shared/space-kinds'
import type { Space } from '#shared/types'

useHead({ title: 'Harbor PMS · Spaces' })

const { data: spacesData, refresh } = await useFetch<Space[]>('/api/spaces', {
  default: () => [],
})
const spaces = computed(() => spacesData.value ?? [])

const editingId = ref<number | null>(null)
const busyId = ref<number | null>(null)

const active = computed(() => spaces.value.filter((s) => s.status === 'active'))
const archived = computed(
  () => spaces.value.filter((s) => s.status === 'archived'),
)
const beds = computed(() => active.value.reduce((n, s) => n + s.capacity, 0))

async function createSpace(payload: SpaceInput) {
  await $fetch('/api/spaces', { method: 'POST', body: payload })
  await refresh()
}

async function updateSpace(id: number, payload: SpaceInput) {
  await $fetch(`/api/spaces/${id}`, { method: 'PUT', body: payload })
  editingId.value = null
  await refresh()
}

async function toggleStatus(space: Space) {
  busyId.value = space.id
  try {
    await $fetch(`/api/spaces/${space.id}/status`, {
      method: 'POST',
      body: { status: space.status === 'active' ? 'archived' : 'active' },
    })
    await refresh()
  } finally {
    busyId.value = null
  }
}

function initialFor(space: Space) {
  return {
    name: space.name,
    kind: space.kind,
    capacity: String(space.capacity),
    rate: space.rate_cents === null ? '' : String(space.rate_cents / 100),
    notes: space.notes ?? '',
  }
}
</script>

<template>
  <div class="page page-wrap">
    <div class="page-head">
      <div>
        <p class="kicker">Inventory</p>
        <h1 class="title">Spaces</h1>
        <p class="subtitle">
          {{ active.length }} bookable · sleeps {{ beds }}<template
            v-if="archived.length"
          >
            · {{ archived.length }} archived</template
          >
        </p>
      </div>
      <NuxtLink to="/reservations" class="btn btn-ghost">
        View reservations
      </NuxtLink>
    </div>

    <div style="margin-top: 2rem">
      <SpaceForm
        title="Add a space"
        submit-label="Add space"
        :on-save="createSpace"
      />
    </div>

    <div v-if="spaces.length === 0" class="panel empty">
      No spaces yet. Add your first room above — guests can't be assigned one
      until you do.
    </div>

    <div v-else class="stack" style="margin-top: 2rem">
      <template v-for="space in spaces" :key="space.id">
        <SpaceForm
          v-if="editingId === space.id"
          :title="`Edit ${space.name}`"
          submit-label="Save changes"
          :initial="initialFor(space)"
          :on-save="(payload) => updateSpace(space.id, payload)"
          :on-cancel="() => (editingId = null)"
        />
        <article v-else class="card" :class="{ 'is-muted': space.status === 'archived' }">
          <div class="card-head">
            <div>
              <div class="chip-row">
                <h2 class="card-title">{{ space.name }}</h2>
                <span class="badge badge-kind">
                  {{ SPACE_KIND_LABELS[space.kind] }}
                </span>
                <span v-if="space.status === 'archived'" class="badge">
                  Archived
                </span>
              </div>
              <div class="meta-row">
                <span>
                  Sleeps {{ space.capacity }} guest{{
                    space.capacity === 1 ? '' : 's'
                  }}
                </span>
                <span>
                  {{
                    formatRate(space.rate_cents)
                      ? `${formatRate(space.rate_cents)} / night`
                      : 'No rate set'
                  }}
                </span>
              </div>
              <p v-if="space.notes" class="note">{{ space.notes }}</p>
            </div>

            <div class="card-actions">
              <button
                type="button"
                class="btn btn-sm btn-ghost"
                @click="editingId = space.id"
              >
                Edit
              </button>
              <button
                type="button"
                class="btn btn-sm btn-ghost"
                :disabled="busyId === space.id"
                @click="toggleStatus(space)"
              >
                {{ space.status === 'archived' ? 'Restore' : 'Archive' }}
              </button>
            </div>
          </div>
        </article>
      </template>
    </div>
  </div>
</template>
